sudo: required
language: node_js
cache:
  yarn: true
notifications:
  email: false
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
branches:
  only:
    - master
env:
  global:
    - CXX=g++-4.8
    - NODE_ENV="test"
node_js:
  - "10"
  - "8"
script:
  - make test-coveralls
